LIBS     = -O2 -liostream -lfstream -lstdlib -lstring
CC=g++
OBJECTS=main.o foo.o
prog: $(OBJECTS)
	$(CC) -o prog main.o foo.o

main.o: src/main.cc
	$(CC) -c src/main.cc
	
foo.o: src/foo.cc
	$(CC) -c src/foo.cc

clean:
	rm prog
	rm $(OBJECTS)
