LIBS     = -O2 -liostream -lfstream -lstdlib -lstring
CC=g++
OBJECTS=main.o addiere.o
prog: $(OBJECTS)
	$(CC) -o prog $(OBJECTS) 

main.o: src/main.cc
	$(CC) -c src/main.cc -I ./src
	
addiere.o: src/addiere.cc
	$(CC) -c src/addiere.cc

clean:
	rm prog
	rm $(OBJECTS)
